import type { PublicArticle, PublicCrazyMatch, PublicEditorialSource, PublicRadarItem, PublicTalent } from "./publicWebsiteTypes";

export const MOCK_PUBLIC_EDITORIAL_SOURCES: readonly PublicEditorialSource[] = [
  { id: "source-original-magazine", label: "Analisi originale Regista Avanzato", type: "original", publicUrl: null, verified: true, publiclyVisible: true },
  { id: "source-story-library", label: "Story Library — contenuto mock approvato", type: "story_library", publicUrl: "/storie", verified: true, publiclyVisible: true },
  { id: "source-echo", label: "Historical Echo — confronto mock approvato", type: "historical_echo", publicUrl: "/il-calcio-si-ripete", verified: true, publiclyVisible: true },
  { id: "source-internal", label: "Nota editoriale interna", type: "manual_research", publicUrl: null, verified: false, publiclyVisible: false },
];

export const MOCK_PUBLIC_ARTICLES: readonly PublicArticle[] = [
  { id: "article-4-4", slug: "otto-gol-e-una-domanda", title: "Otto gol e una domanda: il calcio si ripete?", kicker: "Storia di copertina", summary: "Un 4–4 mock diventa il punto di partenza per leggere ritmo, memoria e differenze tra partite lontane.", previewText: "Il risultato attira l'occhio, ma il valore editoriale nasce dal confronto prudente tra contesti differenti.", bodySections: [{ id: "opening", heading: null, paragraphs: ["Una partita mock termina 4–4. Non è il numero, da solo, a raccontare la storia: sono i cambi di inerzia, le scelte e ciò che resta dopo il fischio finale.", "La Story Library suggerisce un precedente narrativo. Historical Echo mette i due episodi in dialogo senza dichiararli equivalenti."] }, { id: "method", heading: "Somiglianze e differenze", paragraphs: ["Il confronto è stato approvato come dimostrazione editoriale. Nomi, dati e riferimenti storici reali dovranno essere verificati prima dell'uso produttivo."] }], category: "historical_echo", format: "feature", status: "published", visibility: "public_full", authorLabel: "Redazione Regista Avanzato", publishedAt: "2026-08-24T10:00:00.000Z", readingMinutes: 5, tags: ["4-4", "storie", "historical echo"], featured: true, sources: [MOCK_PUBLIC_EDITORIAL_SOURCES[0], MOCK_PUBLIC_EDITORIAL_SOURCES[1], MOCK_PUBLIC_EDITORIAL_SOURCES[2]], internalNotes: [], autoPublished: false },
  { id: "article-talent", slug: "regista-u21-da-seguire", title: "Un regista U21 da seguire, con prudenza", kicker: "Talent Radar", summary: "Profilo editoriale mock di un giovane centrocampista: segnali interessanti, nessuna sentenza di scouting.", previewText: "Visione tra le linee e ritmo sono spunti da osservare nel tempo, non una certificazione professionale.", bodySections: [{ id: "profile", heading: "Il profilo", paragraphs: ["Il giocatore è interamente fittizio e serve a mostrare il formato futuro del Talent Radar."] }], category: "talento", format: "profile", status: "approved", visibility: "public_preview", authorLabel: "Redazione Regista Avanzato", publishedAt: null, readingMinutes: 4, tags: ["U21", "regista", "talento"], featured: true, sources: [MOCK_PUBLIC_EDITORIAL_SOURCES[0]], internalNotes: [], autoPublished: false },
  { id: "article-numbers", slug: "numeri-della-settimana", title: "I numeri della settimana", kicker: "Stats Hub", summary: "Una lettura mock dei segnali statistici principali, con schede complete disponibili tramite login gratuito.", previewText: "Risultati e classifiche restano pubblici; statistiche complete e schede approfondite richiedono un account free.", bodySections: [{ id: "numbers", heading: "Accesso free", paragraphs: ["Questo corpo dimostrativo rappresenta la parte riservata all'utente autenticato."] }], category: "numeri", format: "roundup", status: "published", visibility: "login_required", authorLabel: "Data desk Regista Avanzato", publishedAt: "2026-08-23T09:00:00.000Z", readingMinutes: 6, tags: ["statistiche", "classifiche"], featured: false, sources: [MOCK_PUBLIC_EDITORIAL_SOURCES[0], MOCK_PUBLIC_EDITORIAL_SOURCES[3]], internalNotes: ["Dati reali non collegati."], autoPublished: false },
  { id: "article-minor-leagues", slug: "segnali-dai-campionati-minori", title: "Segnali dai campionati minori", kicker: "Report editoriale", summary: "Anteprima di un report sui campionati meno raccontati, destinato al canale editoriale Substack.", previewText: "Una selezione settimanale, non un flusso live e non una promessa di copertura completa.", bodySections: [{ id: "report", heading: "Report completo", paragraphs: ["Contenuto mock destinato al futuro report esterno."] }], category: "campionati_minori", format: "roundup", status: "approved", visibility: "substack_only", authorLabel: "Redazione Regista Avanzato", publishedAt: null, readingMinutes: 8, tags: ["campionati minori", "weekly report"], featured: false, sources: [MOCK_PUBLIC_EDITORIAL_SOURCES[0]], internalNotes: [], autoPublished: false },
  { id: "article-draft", slug: "bozza-tattica-interna", title: "Bozza tattica interna", kicker: "Non pubblico", summary: "Record mock privato.", previewText: "Non pubblico.", bodySections: [], category: "tattica", format: "analysis", status: "draft", visibility: "private_admin", authorLabel: "Redazione", publishedAt: null, readingMinutes: 3, tags: [], featured: false, sources: [MOCK_PUBLIC_EDITORIAL_SOURCES[3]], internalNotes: ["Fact-check incompleto."], autoPublished: false },
  { id: "article-rejected", slug: "articolo-rifiutato", title: "Articolo rifiutato", kicker: "Non pubblico", summary: "Record mock rifiutato.", previewText: "Non pubblico.", bodySections: [], category: "mercato", format: "news_brief", status: "rejected", visibility: "private_admin", authorLabel: "Redazione", publishedAt: null, readingMinutes: 2, tags: [], featured: false, sources: [], internalNotes: ["Fonte insufficiente."], autoPublished: false },
];

export const MOCK_PUBLIC_TALENTS: readonly PublicTalent[] = [
  { id: "talent-luca-ferri", slug: "luca-ferri", name: "Luca Ferri", role: "Centrocampista", ageLabel: "U21 · profilo mock", competitionLabel: "Campionato dimostrativo", editorialSummary: "Un regista fittizio usato per mostrare come raccontare un talento senza formulare certezze premature.", whyWatch: "Orientamento del corpo e ricerca della verticalità sono temi da osservare su più partite.", status: "published", visibility: "public", tags: ["regista", "U21"], reportAvailability: "substack_candidate", scoutingDisclaimer: "Profilo editoriale mock: non è scouting professionale certificato." },
  { id: "talent-mateo-silva", slug: "mateo-silva", name: "Mateo Silva", role: "Ala", ageLabel: "U20 · profilo mock", competitionLabel: "Sud America mock", editorialSummary: "Accelerazioni e uno contro uno sono segnali narrativi da verificare nel tempo.", whyWatch: "Può diventare un tema del weekend, senza trasformare una singola prestazione in una previsione.", status: "approved", visibility: "public", tags: ["ala", "dribbling"], reportAvailability: "site_preview", scoutingDisclaimer: "Osservazione editoriale dimostrativa, non valutazione professionale." },
  { id: "talent-private", slug: "talento-da-verificare", name: "Talento da verificare", role: "Attaccante", ageLabel: "Età da verificare", competitionLabel: "Fonte incompleta", editorialSummary: "Record interno.", whyWatch: "Dati insufficienti.", status: "pending_review", visibility: "private_admin", tags: [], reportAvailability: "site_preview", scoutingDisclaimer: "Non pubblicabile." },
];

export const MOCK_PUBLIC_RADAR_ITEMS: readonly PublicRadarItem[] = [
  { id: "radar-talent", slug: "giovane-regista", type: "talent_radar", title: "Un giovane regista entra nel radar", summary: "Segnale mock basato su una prestazione da contestualizzare su più gare.", signalLabel: "Da seguire", status: "approved", visibility: "public", relatedHref: "/talenti", internalScore: 82, internalWarnings: [], certaintyClaimed: false },
  { id: "radar-match", slug: "weekend-4-4", type: "match_radar", title: "Il 4–4 del weekend", summary: "Una partita dimostrativa scelta per ritmo e cambi di inerzia.", signalLabel: "Partita da rivedere", status: "published", visibility: "public", relatedHref: "/partite-pazze", internalScore: 91, internalWarnings: [], certaintyClaimed: false },
  { id: "radar-echo", slug: "echo-otto-gol", type: "historical_echo", title: "Otto gol, un possibile eco", summary: "Il confronto è uno spunto editoriale approvato, non una equivalenza storica.", signalLabel: "Collegamento narrativo", status: "approved", visibility: "public", relatedHref: "/il-calcio-si-ripete", internalScore: 88, internalWarnings: [], certaintyClaimed: false },
  { id: "radar-watchlist", slug: "watchlist-weekend", type: "weekly_watchlist", title: "Tre temi per il weekend", summary: "Watchlist mock con talento, partita e storia da seguire.", signalLabel: "Watchlist", status: "published", visibility: "public", relatedHref: "/watchlist", internalScore: null, internalWarnings: [], certaintyClaimed: false },
  { id: "radar-private", slug: "segnale-non-verificato", type: "minor_league_signal", title: "Segnale non verificato", summary: "Record privato.", signalLabel: "Non pubblico", status: "pending_review", visibility: "private_admin", relatedHref: null, internalScore: 39, internalWarnings: ["Fonte incompleta"], certaintyClaimed: false },
];

export const MOCK_PUBLIC_CRAZY_MATCHES: readonly PublicCrazyMatch[] = [
  { id: "crazy-4-4", slug: "aurora-borgo-4-4", competitionLabel: "Campionato mock", homeTeam: "Aurora FC", awayTeam: "Borgo United", homeScore: 4, awayScore: 4, dateLabel: "18 agosto 2026", editorialSummary: "Otto gol e continui cambi di inerzia in una partita completamente dimostrativa.", whyItMatters: "Il trigger è stato revisionato e collegato a un Historical Echo pubblico.", status: "published", visibility: "public", historicalEchoHref: "/il-calcio-si-ripete/otto-gol-stesso-copione", reviewedTrigger: true, autoPublished: false },
  { id: "crazy-5-4", slug: "riviera-porto-5-4", competitionLabel: "Coppa mock", homeTeam: "Riviera", awayTeam: "Porto Vecchio", homeScore: 5, awayScore: 4, dateLabel: "21 agosto 2026", editorialSummary: "Nove gol in un esempio editoriale che mostra il formato futuro della sezione.", whyItMatters: "Il risultato è eccezionale, ma ogni dettaglio resta mock e non genera pubblicazione automatica.", status: "approved", visibility: "public", historicalEchoHref: null, reviewedTrigger: true, autoPublished: false },
  { id: "crazy-private", slug: "trigger-da-rivedere", competitionLabel: "Fonte incompleta", homeTeam: "Squadra A", awayTeam: "Squadra B", homeScore: 6, awayScore: 3, dateLabel: "Data da verificare", editorialSummary: "Trigger non revisionato.", whyItMatters: "Non pubblico.", status: "pending_review", visibility: "private_admin", historicalEchoHref: null, reviewedTrigger: false, autoPublished: false },
];
