import { MOCK_ARTICLE_DRAFTS } from "../articleGenerator/mockArticleDrafts";
import { MOCK_HISTORICAL_ECHO_DATA } from "../historicalEcho/mockHistoricalEchoData";
import { MOCK_NEWS_RADAR_DATA } from "../newsRadar/mockNewsRadarData";
import { MOCK_NEWSLETTER_DRAFTS } from "../newsletterGenerator/mockNewsletterDrafts";
import { MOCK_STORY_LIBRARY } from "../storyLibrary/mockStoryLibrary";
import { MOCK_VIDEO_RADAR_ITEMS } from "../videoRadar/mockVideoRadarData";
import { MOCK_VIDEO_SCRIPTS } from "../videoScriptGenerator/mockVideoScripts";
import type { DailyRadarCollectionResult, DailyRadarSignal, DailyRadarSignalType, DailyRadarSource, DailyRadarSourceType, DailyRadarWarningCode } from "./dailyRadarTypes";

const NOW = "2026-08-25T17:00:00.000Z";
const source = (type: DailyRadarSourceType, referenceId: string, label: string, shortSummary: string, official = false, verified = true, weak = false): DailyRadarSource => ({ id: `daily-source-${type}-${referenceId}`, type, referenceId, label, shortSummary, official, verified, weak, referenceUrl: null, copiedLongText: false, downloadedVideo: false });
const signal = (type: DailyRadarSignalType, referenceId: string, title: string, summary: string, sourceItem: DailyRadarSource, options: Partial<Omit<DailyRadarSignal, "id" | "type" | "title" | "summary" | "sourceIds" | "detectedAt">> = {}): DailyRadarSignal => ({ id: `daily-signal-${type}-${referenceId}`, type, title, summary, sourceIds: [sourceItem.id], officialSource: sourceItem.official, verifiedSources: sourceItem.verified, strongTrigger: false, italianConnection: false, usefulVideoRadar: false, historicalEchoStrength: "none", hasExistingSources: sourceItem.verified, warningCodes: [], detectedAt: NOW, ...options });

export function collectDailyRadarSignals(): DailyRadarCollectionResult { const sources: DailyRadarSource[] = []; const signals: DailyRadarSignal[] = []; const add = (item: DailyRadarSource, radarSignal: DailyRadarSignal) => { sources.push(item); signals.push(radarSignal); };
  const match = MOCK_HISTORICAL_ECHO_DATA[0]?.relatedMatches.find((item) => item.isModern); if (match) { const s = source("match_import", match.id, `${match.label} ${match.scoreline}`, `Trigger partita mock del ${match.dateLabel}.`); add(s, signal("crazy_match", match.id, `${match.label}: ${match.scoreline}`, "Otto gol e cambi di inerzia suggeriscono una review editoriale.", s, { strongTrigger: true })); }
  const stats = source("stats_import", "mock-luca-ferri-full-official", "Snapshot statistiche FULL_OFFICIAL mock", "Un centrocampista U21 mock registra 1 gol, 2 assist e 4 key pass nello snapshot già disponibile."); add(stats, signal("stats_spike", "mock-luca-ferri-full-official", "Segnale statistico U21 da contestualizzare", "Picco statistico mock da verificare su più partite, senza trasformarlo in scouting certificato.", stats, { strongTrigger: true }));
  for (const item of MOCK_NEWS_RADAR_DATA.slice(0, 5)) { const official = item.sources.some((entry) => entry.reliability === "official"); const rumor = item.signals.some((entry) => entry.type === "rumor_da_verificare"); const s = source("news_radar", item.id, item.title, item.summary, official, item.reviewedByHuman && !rumor, rumor); const type: DailyRadarSignalType = rumor ? "rumor_to_review" : item.category === "talent_signal" ? "talent_signal" : "official_news"; const warnings: DailyRadarWarningCode[] = rumor ? ["rumor", "weak_source"] : []; add(s, signal(type, item.id, item.title, item.summary, s, { strongTrigger: item.score.total >= 70, warningCodes: warnings })); }
  for (const item of MOCK_STORY_LIBRARY.filter((story) => story.status === "approved" || story.status === "published").slice(0, 2)) { const s = source("story_library", item.id, item.title, item.summary); add(s, signal(item.category === "talent_story" ? "young_player" : "article_seed", item.id, item.title, item.summary, s, { strongTrigger: item.category === "talent_story" })); }
  for (const item of MOCK_HISTORICAL_ECHO_DATA.filter((echo) => echo.reviewedByHuman && (echo.status === "approved" || echo.status === "published")).slice(0, 2)) { const s = source("historical_echo", item.id, item.title, item.summary); add(s, signal("historical_echo", item.id, item.title, item.summary, s, { historicalEchoStrength: item.score.confidence === "high" ? "strong" : "medium", strongTrigger: item.score.confidence === "high" })); }
  for (const item of MOCK_VIDEO_RADAR_ITEMS.filter((video) => video.status === "approved").slice(0, 3)) { const s = source("video_radar", item.id, item.title, item.summary, false, true); add(s, signal("video_watch", item.id, item.title, item.summary, s, { usefulVideoRadar: true, warningCodes: item.officialVideoUrl ? [] : ["copyright_uncertain"] })); }
  for (const item of MOCK_ARTICLE_DRAFTS.filter((draft) => draft.riskLevel !== "blocked").slice(0, 3)) { const s = source("article_generator", item.id, item.title, item.subtitle, false, item.riskLevel !== "high", item.riskLevel === "high"); add(s, signal("article_seed", item.id, item.title, item.subtitle, s, { warningCodes: item.riskLevel === "high" ? ["incomplete_data"] : [] })); }
  for (const item of MOCK_NEWSLETTER_DRAFTS.filter((draft) => draft.riskLevel !== "blocked").slice(0, 4)) { const s = source("newsletter_generator", item.id, item.title, item.preheader, false, item.riskLevel !== "high", item.riskLevel === "high"); add(s, signal("newsletter_seed", item.id, item.title, item.preheader, s, { warningCodes: item.riskLevel === "high" ? ["incomplete_data"] : [] })); }
  for (const item of MOCK_VIDEO_SCRIPTS.filter((draft) => draft.riskLevel !== "blocked").slice(0, 4)) { const s = source("video_script_generator", item.id, item.title, item.hook.text, false, item.riskLevel !== "high", item.riskLevel === "high"); add(s, signal(item.format === "creator_pack_item" ? "creator_pack_seed" : "reel_seed", item.id, item.title, item.hook.text, s, { usefulVideoRadar: true, warningCodes: item.riskLevel === "high" ? ["copyright_uncertain"] : [] })); }
  return { sources, signals, warnings: ["Raccolta mock offline: nessun dato live, provider, Apify o Supabase."] }; }
