import { calculateNewsRadarScore } from "./newsRadarScoring";
import type { NewsRadarItem, NewsRadarSource } from "./newsRadarTypes";

export const MOCK_NEWS_RADAR_SOURCES: readonly NewsRadarSource[] = [
  { id: "news-source-club", name: "Club Aurora — fonte ufficiale mock", type: "official_club", reliability: "official", referenceUrl: null, referenceLabel: "Comunicazione ufficiale dimostrativa", publiclyVisible: true, internalNote: null, checkedOfflineOnly: true },
  { id: "news-source-league", name: "Lega dimostrativa", type: "official_league", reliability: "official", referenceUrl: null, referenceLabel: "Nota gara mock", publiclyVisible: true, internalNote: null, checkedOfflineOnly: true },
  { id: "news-source-media", name: "Testata sportiva mock", type: "media_outlet", reliability: "high", referenceUrl: null, referenceLabel: "Analisi editoriale dimostrativa", publiclyVisible: true, internalNote: "In produzione verificare autore, data e URL.", checkedOfflineOnly: true },
  { id: "news-source-manual", name: "Ricerca originale redazione", type: "manual_research", reliability: "high", referenceUrl: null, referenceLabel: "Appunti originali mock", publiclyVisible: true, internalNote: null, checkedOfflineOnly: true },
  { id: "news-source-database", name: "Segnale database mock", type: "database_signal", reliability: "medium", referenceUrl: null, referenceLabel: "Trigger strutturato dimostrativo", publiclyVisible: false, internalNote: "Non è sufficiente come fonte narrativa.", checkedOfflineOnly: true },
  { id: "news-source-rumor", name: "Rumor non verificato mock", type: "rumor", reliability: "unverified", referenceUrl: null, referenceLabel: "Voce dimostrativa senza conferma", publiclyVisible: false, internalNote: "Seconda fonte assente.", checkedOfflineOnly: true },
  { id: "news-source-social", name: "Segnale social mock", type: "social_signal", reliability: "low", referenceUrl: null, referenceLabel: "Post non verificato", publiclyVisible: false, internalNote: "Non pubblicabile.", checkedOfflineOnly: true },
  { id: "news-source-unknown", name: "Fonte da identificare", type: "unknown", reliability: "unverified", referenceUrl: null, referenceLabel: "Provenienza incompleta", publiclyVisible: false, internalNote: "Blocco pubblico.", checkedOfflineOnly: true },
];

type ItemWithoutScore = Omit<NewsRadarItem, "score" | "priority">;
function withScore(item: ItemWithoutScore): NewsRadarItem {
  const result = calculateNewsRadarScore({ sources: item.sources, signals: item.signals, duplicateCandidate: item.duplicateCandidate, sourceMissing: item.sources.length === 0 });
  return { ...item, ...result };
}

export const MOCK_NEWS_RADAR_DATA: readonly NewsRadarItem[] = [
  withScore({ id: "news-official-injury", slug: "comunicato-aurora-recupero", title: "Club Aurora: aggiornamento mock sul recupero", summary: "Una comunicazione ufficiale dimostrativa viene trasformata in una notizia breve e prudente.", body: ["Il club mock comunica l'avvio di un percorso di recupero. Tempi e diagnosi reali non sono presenti in questo esempio.", "La notizia resta collegata alla fonte ufficiale e non aggiunge interpretazioni mediche."], category: "injury_update", status: "published", visibility: "public_full", sources: [MOCK_NEWS_RADAR_SOURCES[0]], signals: [{ id: "sig-official", type: "fonte_ufficiale", label: "Fonte ufficiale mock", strength: "strong" }, { id: "sig-injury", type: "infortunio", label: "Aggiornamento recupero", strength: "medium" }], reviewStatus: "approved", editorialSuggestion: { headline: "Club Aurora: aggiornamento sul recupero", cautiousHeadline: "Il Club Aurora comunica un aggiornamento mock sul recupero", angle: "News breve basata soltanto sul comunicato.", destinations: ["article", "weekly_digest"], status: "idea_only" }, relatedEntities: [{ type: "club", id: "mock-aurora", label: "Aurora FC", href: "/squadre/mock-aurora" }], internalWarnings: [], duplicateCandidate: false, reviewedByHuman: true, certaintyClaimed: false, autoPublished: false, publishedAt: "2026-08-25T08:00:00.000Z", createdAt: "2026-08-25T07:30:00.000Z", updatedAt: "2026-08-25T08:00:00.000Z" }),
  withScore({ id: "news-talent", slug: "giovane-regista-segnale", title: "Un giovane regista entra nel radar", summary: "Una testata mock segnala una prestazione interessante, presentata come tema da seguire e non come certezza.", body: ["Il profilo completo resta in revisione. Una singola partita non basta per una valutazione stabile."], category: "talent_signal", status: "approved", visibility: "public_preview", sources: [MOCK_NEWS_RADAR_SOURCES[2]], signals: [{ id: "sig-talent", type: "giovane_talento", label: "Giovane talento", strength: "strong" }, { id: "sig-video", type: "possibile_video", label: "Possibile Video Radar", strength: "medium" }], reviewStatus: "approved", editorialSuggestion: { headline: "Il giovane regista da osservare", cautiousHeadline: "Un giovane regista da osservare nelle prossime gare", angle: "Seguire il profilo nel tempo senza formulare scouting certificato.", destinations: ["public_radar", "video_radar", "weekly_digest"], status: "idea_only" }, relatedEntities: [{ type: "player", id: "mock-luca-ferri", label: "Luca Ferri — mock", href: "/giocatori/mock-luca-ferri" }], internalWarnings: [], duplicateCandidate: false, reviewedByHuman: true, certaintyClaimed: false, autoPublished: false, publishedAt: null, createdAt: "2026-08-24T18:00:00.000Z", updatedAt: "2026-08-25T08:00:00.000Z" }),
  withScore({ id: "news-tactical", slug: "pressione-alta-nota-tattica", title: "Pressione alta: una nota tattica dal match mock", summary: "Analisi originale basata su un evento dimostrativo e su una fonte gara ufficiale mock.", body: ["La lettura completa sarà disponibile all'account free quando Auth e dati reali saranno collegati."], category: "tactical_analysis", status: "approved", visibility: "login_required", sources: [MOCK_NEWS_RADAR_SOURCES[1], MOCK_NEWS_RADAR_SOURCES[3]], signals: [{ id: "sig-story", type: "possibile_storia", label: "Possibile approfondimento", strength: "medium" }], reviewStatus: "approved", editorialSuggestion: { headline: "Come cambia la pressione alta", cautiousHeadline: "Una lettura della pressione alta nel match mock", angle: "Analisi tattica prudente.", destinations: ["article", "weekly_digest"], status: "idea_only" }, relatedEntities: [{ type: "match", id: "mock-match-tactical", label: "Match tattico mock", href: "/competizioni/mock/partite/mock-match-tactical" }], internalWarnings: [], duplicateCandidate: false, reviewedByHuman: true, certaintyClaimed: false, autoPublished: false, publishedAt: null, createdAt: "2026-08-24T12:00:00.000Z", updatedAt: "2026-08-25T08:00:00.000Z" }),
  withScore({ id: "news-cultural", slug: "maglie-e-memoria", title: "Maglie e memoria: uno spunto culturale", summary: "Anteprima editoriale originale destinata a un possibile approfondimento Substack.", body: ["Il report completo resta esterno al sito e non viene generato automaticamente."], category: "cultural_story", status: "approved", visibility: "substack_only", sources: [MOCK_NEWS_RADAR_SOURCES[3]], signals: [{ id: "sig-substack", type: "possibile_substack", label: "Possibile Substack", strength: "medium" }], reviewStatus: "approved", editorialSuggestion: { headline: "Maglie e memoria", cautiousHeadline: "Un possibile viaggio tra maglie e memoria", angle: "Contenuto culturale originale.", destinations: ["substack_free", "weekly_digest"], status: "idea_only" }, relatedEntities: [{ type: "story", id: "story-mock-4-4", label: "Story Library mock", href: "/storie/il-4-4-che-si-ripete" }], internalWarnings: [], duplicateCandidate: false, reviewedByHuman: true, certaintyClaimed: false, autoPublished: false, publishedAt: null, createdAt: "2026-08-24T10:00:00.000Z", updatedAt: "2026-08-25T08:00:00.000Z" }),
  withScore({ id: "news-rumor", slug: "possibile-interesse-da-verificare", title: "Possibile interesse di mercato, ancora senza conferme", summary: "Rumor mock mantenuto nella queue privata in attesa di fonti indipendenti.", body: [], category: "transfer_market", status: "pending_review", visibility: "private_admin", sources: [MOCK_NEWS_RADAR_SOURCES[5]], signals: [{ id: "sig-transfer", type: "trasferimento", label: "Mercato", strength: "medium" }, { id: "sig-rumor", type: "rumor_da_verificare", label: "Rumor", strength: "strong" }], reviewStatus: "needs_sources", editorialSuggestion: { headline: "Interesse di mercato", cautiousHeadline: "Secondo una voce non verificata, potrebbe esserci un interesse", angle: "Non sviluppare senza conferme.", destinations: [], status: "idea_only" }, relatedEntities: [], internalWarnings: ["Seconda fonte assente.", "Pubblico bloccato."], duplicateCandidate: false, reviewedByHuman: false, certaintyClaimed: false, autoPublished: false, publishedAt: null, createdAt: "2026-08-25T07:00:00.000Z", updatedAt: "2026-08-25T07:00:00.000Z" }),
  withScore({ id: "news-data-candidate", slug: "risultato-storico-candidate", title: "Un risultato fuori scala entra nella queue", summary: "Trigger database mock da collegare a fonti e Story Library prima della review.", body: [], category: "historical_echo_candidate", status: "candidate", visibility: "private_admin", sources: [MOCK_NEWS_RADAR_SOURCES[4]], signals: [{ id: "sig-crazy", type: "partita_pazza", label: "Partita pazza", strength: "strong" }, { id: "sig-historic", type: "risultato_storico", label: "Possibile risultato storico", strength: "strong" }, { id: "sig-story-2", type: "possibile_storia", label: "Possibile Historical Echo", strength: "medium" }], reviewStatus: "fact_check", editorialSuggestion: { headline: "Il risultato che richiama la storia", cautiousHeadline: "Un risultato mock potrebbe suggerire un precedente", angle: "Verificare scoreline, contesto e fonti.", destinations: ["historical_echo", "public_radar", "weekly_digest"], status: "idea_only" }, relatedEntities: [{ type: "historical_echo", id: "echo-mock-4-4", label: "Historical Echo mock", href: "/il-calcio-si-ripete/otto-gol-stesso-copione" }], internalWarnings: ["Il trigger database non è una fonte narrativa."], duplicateCandidate: false, reviewedByHuman: false, certaintyClaimed: false, autoPublished: false, publishedAt: null, createdAt: "2026-08-25T06:30:00.000Z", updatedAt: "2026-08-25T06:30:00.000Z" }),
  withScore({ id: "news-controversy", slug: "controversia-social-rifiutata", title: "Controversia social non verificata", summary: "Segnale mock rifiutato per affidabilità insufficiente.", body: [], category: "controversy", status: "rejected", visibility: "private_admin", sources: [MOCK_NEWS_RADAR_SOURCES[6]], signals: [{ id: "sig-controversy", type: "controversia", label: "Controversia", strength: "strong" }], reviewStatus: "rejected", editorialSuggestion: { headline: "Nessun titolo pubblico", cautiousHeadline: "Segnale non verificato", angle: "Non pubblicare.", destinations: [], status: "idea_only" }, relatedEntities: [], internalWarnings: ["Fonte social bassa.", "Rischio reputazionale."], duplicateCandidate: true, reviewedByHuman: true, certaintyClaimed: false, autoPublished: false, publishedAt: null, createdAt: "2026-08-24T22:00:00.000Z", updatedAt: "2026-08-25T06:00:00.000Z" }),
  withScore({ id: "news-draft", slug: "bozza-senza-fonte", title: "Bozza senza fonte", summary: "Idea incompleta conservata soltanto nell'admin mock.", body: [], category: "match_preview", status: "draft", visibility: "private_admin", sources: [], signals: [], reviewStatus: "needs_sources", editorialSuggestion: { headline: "Bozza", cautiousHeadline: "Bozza", angle: "Aggiungere fonti.", destinations: [], status: "idea_only" }, relatedEntities: [], internalWarnings: ["Fonte mancante."], duplicateCandidate: false, reviewedByHuman: false, certaintyClaimed: false, autoPublished: false, publishedAt: null, createdAt: "2026-08-25T05:00:00.000Z", updatedAt: "2026-08-25T05:00:00.000Z" }),
];
