import type { MockSearchIndexItem } from "./searchTypes";

/** Contenuti dimostrativi esplicitamente mock: nessuna riga proviene da provider o Supabase. */
export const MOCK_SEARCH_INDEX: readonly MockSearchIndexItem[] = [
  { id: "mock-player-regista", entityType: "players", title: "Luca Ferri", summary: "Centrocampista creativo U21 — profilo dimostrativo.", href: "/giocatori/mock-luca-ferri", country: "Italia", competitionId: "serie-a", season: "2026", occurredAt: null, hasOfficialHighlights: false, hasVideoRadar: true, tags: ["U21", "regista", "mock"], searchableText: "luca ferri italia serie a u21 regista talento" },
  { id: "mock-team-aurora", entityType: "teams", title: "Aurora FC", summary: "Squadra fittizia usata per provare filtri e risultati.", href: "/squadre/mock-aurora-fc", country: "Italia", competitionId: "serie-a", season: "2026", occurredAt: null, hasOfficialHighlights: false, hasVideoRadar: false, tags: ["squadra", "mock"], searchableText: "aurora fc italia serie a squadra" },
  { id: "mock-competition-serie-a", entityType: "competitions", title: "Serie A", summary: "Configurazione demo della competizione FULL_OFFICIAL.", href: "/competizioni/serie-a", country: "Italia", competitionId: "serie-a", season: "2026", occurredAt: null, hasOfficialHighlights: true, hasVideoRadar: true, tags: ["Italia", "FULL_OFFICIAL"], searchableText: "serie a italia campionato classifica" },
  { id: "mock-match-aurora-borgo", entityType: "matches", title: "Aurora FC 4–4 Borgo United", summary: "Partita fittizia ad alto punteggio per testare i trigger.", href: "/competizioni/serie-a/partite/mock-aurora-borgo", country: "Italia", competitionId: "serie-a", season: "2026", occurredAt: "2026-08-18T19:45:00.000Z", hasOfficialHighlights: true, hasVideoRadar: true, tags: ["4-4", "partita pazza", "mock"], searchableText: "aurora borgo 4 4 partita pazza gol highlights" },
  { id: "mock-story-rimonta", entityType: "stories", title: "La rimonta che cambiò una stagione", summary: "Scheda Story Library dimostrativa.", href: "/storie/mock-rimonta", country: "Italia", competitionId: "serie-a", season: "2026", occurredAt: "2026-08-19T08:00:00.000Z", hasOfficialHighlights: false, hasVideoRadar: false, tags: ["rimonta", "Story Library"], searchableText: "rimonta stagione storia story library" },
  { id: "mock-article-pressing", entityType: "articles", title: "Come cambia il pressing alto", summary: "Articolo editoriale mock sulle tendenze tattiche.", href: "/news/mock-pressing-alto", country: null, competitionId: null, season: "2026", occurredAt: "2026-08-20T10:00:00.000Z", hasOfficialHighlights: false, hasVideoRadar: false, tags: ["tattica", "pressing"], searchableText: "articolo tattica pressing alto analisi" },
  { id: "mock-highlight-official", entityType: "highlights", title: "Highlights ufficiali — Aurora vs Borgo", summary: "Anteprima del record link ufficiale; nessun video ospitato.", href: "/competizioni/serie-a/partite/mock-aurora-borgo", country: "Italia", competitionId: "serie-a", season: "2026", occurredAt: "2026-08-18T22:00:00.000Z", hasOfficialHighlights: true, hasVideoRadar: false, tags: ["link ufficiale", "highlights"], searchableText: "highlights ufficiali aurora borgo video link" },
  { id: "mock-video-radar", entityType: "video_radar", title: "Video Radar — Il regista tra le linee", summary: "Script video originale dimostrativo basato su dati mock.", href: "/video-radar", country: "Italia", competitionId: "serie-a", season: "2026", occurredAt: "2026-08-21T12:00:00.000Z", hasOfficialHighlights: false, hasVideoRadar: true, tags: ["Video Radar", "talento"], searchableText: "video radar regista linee talento analisi" },
  { id: "mock-historical-echo", entityType: "historical_echo", title: "Historical Echo — Un altro 4–4", summary: "Confronto storico fittizio da sottoporre a verifica editoriale.", href: "/il-calcio-si-ripete", country: "Italia", competitionId: "serie-a", season: "2026", occurredAt: "2026-08-22T09:00:00.000Z", hasOfficialHighlights: false, hasVideoRadar: false, tags: ["Historical Echo", "4-4"], searchableText: "historical echo storia 4 4 calcio si ripete" },
  { id: "mock-news-radar", entityType: "news", title: "News Radar — Giovane decisivo", summary: "Segnale news mock, non pubblicato automaticamente.", href: "/news", country: "Francia", competitionId: "ligue-2", season: "2026", occurredAt: "2026-08-23T14:00:00.000Z", hasOfficialHighlights: false, hasVideoRadar: true, tags: ["News Radar", "U21"], searchableText: "news radar giovane u21 decisivo francia ligue 2" },
];
