import { createSafeVisualCue } from "./videoVisualRules";
import { collectVideoScriptSources } from "./videoScriptSourceCollector";
import { buildVideoScriptPrompt } from "./videoScriptPromptBuilder";
import { evaluateVideoScriptRisks } from "./videoScriptRiskRules";
import { buildVideoScriptReviewChecklist } from "./videoScriptReviewRules";
import { formatVideoScript } from "./videoScriptFormatter";
import type { VideoScriptDraft, VideoScriptFactConfidence, VideoScriptGenerationInput, VideoScriptGenerationResult, VideoScriptSection, VideoScriptSource } from "./videoScriptTypes";

const FIXED_TIME = "2026-08-25T16:00:00.000Z";
const duration: Record<VideoScriptGenerationInput["format"], number> = { reel_30: 30, reel_60: 60, short_vertical: 45, video_2_min: 120, video_3_min: 180, tactical_board: 90, talent_profile: 120, historical_echo_video: 150, news_explainer: 90, match_story: 120, creator_pack_item: 30 };
const slugify = (value: string) => value.toLocaleLowerCase("it-IT").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 80) || "video-script";
const sourceIds = (sources: readonly VideoScriptSource[]) => sources.map((source) => source.id);
const confidence = (sources: readonly VideoScriptSource[]): VideoScriptFactConfidence => sources.some((source) => source.factConfidence === "uncertain" || source.factConfidence === "unknown") ? "uncertain" : sources.some((source) => source.factConfidence === "likely") ? "likely" : sources.some((source) => source.factConfidence === "verified") ? "verified" : "opinion";

function buildSections(input: VideoScriptGenerationInput, sources: readonly VideoScriptSource[]): VideoScriptSection[] { const ids = sourceIds(sources); const fact = sources[0]?.shortSummary ?? "Nessun fatto disponibile: aggiungere una fonte prima della produzione."; const angle = input.format === "historical_echo_video" ? "Il confronto è uno spunto editoriale, non un’equivalenza storica." : input.format === "talent_profile" ? "Osserviamo un segnale nel tempo, senza scouting certificato." : input.format === "tactical_board" ? "La lavagna originale illustra il concetto senza clip partita." : "La bozza trasforma il segnale in un racconto originale e prudente."; const total = duration[input.format]; const mid = Math.max(8, Math.floor(total * .35)); return [
  { id: "scene-hook", scene: 1, timing: `0–${Math.min(6, mid)}s`, voiceover: `Hook: ${fact}`, onScreenText: input.title ?? "Un segnale da osservare", visualCues: [createSafeVisualCue({ id: "visual-hook", scene: 1, kind: "original_graphic", description: "Title card e grafica originale con dato o domanda editoriale.", rightsReviewRequired: false, sourceIds: ids })], sourceIds: ids, factConfidence: confidence(sources), productionNotes: ["Voiceover originale.", "Non inserire clip partita."] },
  { id: "scene-context", scene: 2, timing: `${Math.min(6, mid)}–${mid}s`, voiceover: fact, onScreenText: "Fatto / segnale da verificare", visualCues: [createSafeVisualCue({ id: "visual-context", scene: 2, kind: input.format === "tactical_board" ? "tactical_board" : "data_visualization", description: input.format === "tactical_board" ? "Lavagna tattica disegnata internamente." : "Statistica visuale o timeline originale, senza media esterni.", rightsReviewRequired: false, sourceIds: ids })], sourceIds: ids, factConfidence: confidence(sources), productionNotes: ["Controllare nomi, data e punteggio prima di produrre."] },
  { id: "scene-angle", scene: 3, timing: `${mid}–${total}s`, voiceover: angle, onScreenText: "Interpretazione editoriale", visualCues: [createSafeVisualCue({ id: "visual-angle", scene: 3, kind: input.format === "talent_profile" ? "drawn_map_or_lineup" : "original_graphic", description: "Schema, mappa o card conclusiva prodotta internamente.", rightsReviewRequired: false, sourceIds: ids })], sourceIds: ids, factConfidence: "opinion", productionNotes: ["Separare chiaramente interpretazione e fatto.", "Nessun download, reupload o storage di highlights."] },
]; }

export function generateVideoScript(input: VideoScriptGenerationInput): VideoScriptGenerationResult { const collected = collectVideoScriptSources(input); const title = input.title?.trim() || `Bozza ${input.format.replace(/_/g, " ")}`; const sections = buildSections(input, collected.sources); const hook = { text: collected.sources.length ? `Cosa racconta davvero questo segnale? ${collected.sources[0].label}.` : "Hook non disponibile senza fonte verificabile.", style: "question" as const, factConfidence: confidence(collected.sources), sourceIds: sourceIds(collected.sources) }; const cta = { text: input.ctaText?.trim() || "Approfondisci su Regista Avanzato dopo la review editoriale.", destination: input.destination, requiresLinkVerification: true }; const id = input.scriptId ?? `video-${slugify(title)}-${input.format}`; const base: VideoScriptDraft = { id, slug: slugify(title), title, status: collected.sources.length ? "generated" : "draft", visibility: "private_admin", format: input.format, destination: input.destination, tone: input.tone, durationSeconds: duration[input.format], hook, sections, cta, sources: collected.sources, risks: [], riskLevel: "low", reviewChecklist: [], internalPrompt: buildVideoScriptPrompt(input, collected.sources), formattedPreview: "", sourcesToVerify: collected.sources.filter((source) => !source.verifiedForDraft || source.riskFlags.length).map((source) => source.label), reviewedByHuman: false, generatedWithoutExternalAi: true, autoProduce: false, autoPublish: false, createdAt: FIXED_TIME, updatedAt: FIXED_TIME }; const evaluated = evaluateVideoScriptRisks(base); const withReview = { ...base, risks: evaluated.risks, riskLevel: evaluated.riskLevel, reviewChecklist: buildVideoScriptReviewChecklist(evaluated.riskLevel) }; const output = formatVideoScript(withReview); const draft = { ...withReview, formattedPreview: output }; return { success: collected.sources.length > 0 && evaluated.riskLevel !== "blocked", draft, output, warnings: [...collected.warnings, ...evaluated.risks.map((risk) => risk.message)], externalAiCalls: 0, videoGenerations: 0, downloads: 0, uploads: 0, networkCalls: 0, filesWritten: 0, databaseWrites: 0, published: false, produced: false }; }
