import { MOCK_NEWSLETTER_DRAFTS } from "../newsletterGenerator/mockNewsletterDrafts";
import { collectNewsletterSources } from "../newsletterGenerator/newsletterSourceCollector";
import type { NewsletterDraftSourceRef } from "../newsletterGenerator/newsletterGeneratorTypes";
import type { VideoScriptGenerationInput, VideoScriptSource, VideoScriptSourceCollectionResult } from "./videoScriptTypes";

const supportedNewsletterRefs = new Set(["story_library", "news_radar", "historical_echo", "video_radar", "article_draft", "match_trigger"]);
const mapSource = (source: ReturnType<typeof collectNewsletterSources>["sources"][number]): VideoScriptSource => ({ id: `video-${source.id}`, type: source.type === "official_source" ? "official_video_link" : source.type === "minor_league_signal" ? "mock_data" : source.type, referenceId: source.referenceId, label: source.label, shortSummary: source.shortSummary, referenceUrl: source.referenceUrl, factConfidence: source.factConfidence, riskFlags: source.riskFlags.map((flag) => flag === "video_rights" ? "copyright_video" : flag === "unofficial_highlight" ? "unofficial_video" : flag === "scouting_claim" ? "scouting_claim" : flag === "assertive_claim" ? "assertive_claim" : flag === "rumor" ? "rumor" : flag === "injury" ? "injury" : flag === "controversy" ? "controversy" : flag === "unverified_data" ? "unverified_data" : "copyright_video"), verifiedForDraft: source.verifiedForDraft, officialVideoLinkVerified: source.officialLinkVerified, copiedLongText: false, downloadedVideo: false });

function newsletterSource(id: string): VideoScriptSource | null { const draft = MOCK_NEWSLETTER_DRAFTS.find((item) => item.id === id || item.slug === id); if (!draft) return null; return { id: `video-newsletter-${draft.id}`, type: "newsletter_draft", referenceId: draft.id, label: draft.title, shortSummary: draft.preheader, referenceUrl: null, factConfidence: draft.riskLevel === "low" ? "likely" : "uncertain", riskFlags: draft.riskLevel === "blocked" ? ["unverified_data"] : draft.riskLevel === "high" ? ["unverified_data"] : [], verifiedForDraft: draft.riskLevel !== "blocked", officialVideoLinkVerified: false, copiedLongText: false, downloadedVideo: false }; }

export function collectVideoScriptSources(input: Pick<VideoScriptGenerationInput, "sourceRefs">): VideoScriptSourceCollectionResult { const newsletterRefs = input.sourceRefs.filter((ref) => supportedNewsletterRefs.has(ref.type)).map((ref) => ({ type: ref.type, id: ref.id }) as NewsletterDraftSourceRef); const collected = collectNewsletterSources({ sourceRefs: newsletterRefs }); const sources = collected.sources.map(mapSource); const missingRefs = input.sourceRefs.filter((ref) => supportedNewsletterRefs.has(ref.type) && collected.missingRefs.some((missing) => missing.type === ref.type && missing.id === ref.id)); for (const ref of input.sourceRefs.filter((item) => item.type === "newsletter_draft")) { const source = newsletterSource(ref.id); if (source) sources.push(source); else missingRefs.push(ref); } return { sources: sources.filter((source, index) => sources.findIndex((candidate) => candidate.id === source.id) === index), missingRefs, warnings: [...(missingRefs.length ? [`${missingRefs.length} riferimenti mock non risolti.`] : []), ...(sources.length === 0 ? ["Nessuna fonte: script bloccato."] : [])] }; }
