import type { HistoricalEcho, HistoricalEchoSource, HistoricalEchoTrigger } from "./historicalEchoTypes";

export const MOCK_HISTORICAL_ECHO_TRIGGERS: readonly HistoricalEchoTrigger[] = [
  { id: "trigger-modern-4-4", type: "draw_4_4", label: "Aurora FC–Borgo United finisce 4–4", strength: "strong", keywords: ["4-4", "otto gol", "partita memorabile"], modernMatchId: "mock-aurora-borgo", observedAt: "2026-08-18T21:00:00.000Z" },
  { id: "trigger-young-regista", type: "young_player_candidate", label: "Un giovane regista decide la gara mock", strength: "strong", keywords: ["talento", "regista", "U21"], modernMatchId: "mock-riviera-porto", observedAt: "2026-08-22T20:00:00.000Z" },
  { id: "trigger-italian-link", type: "italian_club_mention", label: "Collegamento italiano da verificare", strength: "medium", keywords: ["Italia", "club italiano"], modernMatchId: null, observedAt: "2026-08-23T08:00:00.000Z" },
  { id: "trigger-tactical", type: "similar_tactical_pattern", label: "Somiglianza tattica debole", strength: "weak", keywords: ["pressing", "ritmo"], modernMatchId: "mock-tactical", observedAt: "2026-08-24T08:00:00.000Z" },
];

export const MOCK_HISTORICAL_ECHO_SOURCES: readonly HistoricalEchoSource[] = [
  { id: "echo-source-modern-4-4", type: "modern_match", referenceId: "mock-aurora-borgo", label: "Risultato moderno mock 4–4", verified: true },
  { id: "echo-source-story-4-4", type: "story_library", referenceId: "story-mock-4-4", label: "Story Library — Il 4–4 che si ripete", verified: true },
  { id: "echo-source-talent", type: "story_library", referenceId: "story-mock-talent", label: "Story Library — Il regista tra le linee", verified: true },
  { id: "echo-source-manual", type: "manual_note", referenceId: "note-italy", label: "Nota manuale da verificare", verified: false },
];

const publishedScore = { total: 91, triggerStrength: 34, storySimilarity: 30, sourceQuality: 12, editorialValue: 15, confidence: "high" as const, reasons: ["Trigger 4–4 forte.", "Categoria narrativa coerente.", "Storia approvata."] };
const talentScore = { total: 82, triggerStrength: 34, storySimilarity: 23, sourceQuality: 12, editorialValue: 13, confidence: "high" as const, reasons: ["Trigger giovane decisivo forte.", "Profilo talento coerente.", "Contesto da verificare."] };
const mediumScore = { total: 61, triggerStrength: 24, storySimilarity: 14, sourceQuality: 12, editorialValue: 11, confidence: "medium" as const, reasons: ["Trigger contestuale.", "Affinità parziale."] };
const lowScore = { total: 34, triggerStrength: 12, storySimilarity: 8, sourceQuality: 4, editorialValue: 10, confidence: "low" as const, reasons: ["Trigger debole.", "Fonti insufficienti."] };

export const MOCK_HISTORICAL_ECHO_DATA: readonly HistoricalEcho[] = [
  {
    id: "echo-mock-4-4", slug: "otto-gol-stesso-copione", title: "Otto gol, lo stesso copione?", summary: "Un 4–4 moderno richiama una storia della Story Library, con analogie e differenze da leggere insieme.", type: "scoreline_echo", status: "published", visibility: "public_full", trigger: MOCK_HISTORICAL_ECHO_TRIGGERS[0], score: publishedScore,
    explanation: "Il risultato e il ritmo narrativo sono simili; squadre, epoca e contesto restano differenti e non vengono equiparati.",
    comparisonPoints: [{ id: "score", label: "Risultato", modernValue: "4–4 mock", historicalValue: "4–4 narrativo mock", similarity: "direct" }, { id: "context", label: "Contesto", modernValue: "Gara moderna dimostrativa", historicalValue: "Nota storica dimostrativa", similarity: "contextual" }, { id: "rhythm", label: "Ritmo", modernValue: "Continui cambi di inerzia", historicalValue: "Copione offensivo simile", similarity: "partial" }],
    relatedStory: { storyId: "story-mock-4-4", slug: "il-4-4-che-si-ripete", title: "Il 4–4 che si ripete", category: "legendary_match", summary: "Una storia originale mock su una partita ricca di gol e il suo possibile eco storico." },
    relatedMatches: [{ id: "mock-aurora-borgo", label: "Aurora FC–Borgo United", scoreline: "4–4", dateLabel: "18 agosto 2026", isModern: true }, { id: "mock-historical-4-4", label: "Precedente narrativo mock", scoreline: "4–4", dateLabel: "Data storica da verificare", isModern: false }],
    sources: [MOCK_HISTORICAL_ECHO_SOURCES[0], MOCK_HISTORICAL_ECHO_SOURCES[1]], editorialSuggestion: { headline: "Otto gol, lo stesso copione?", angle: "Confronto editoriale tra due partite senza confondere i rispettivi contesti.", destinations: ["story_library", "future_article", "substack", "video_radar"], status: "idea_only" }, internalWarnings: ["Il precedente reale dovrà essere verificato prima di sostituire il riferimento mock."],
    timeline: [{ id: "today", dateLabel: "18 agosto 2026", title: "Il trigger moderno", description: "Il risultato mock attiva il confronto." }, { id: "review", dateLabel: "24 agosto 2026", title: "Review editoriale", description: "Il collegamento viene approvato come contenuto dimostrativo." }], reviewedByHuman: true, autoPublished: false, createdAt: "2026-08-18T22:00:00.000Z", updatedAt: "2026-08-24T10:00:00.000Z",
  },
  {
    id: "echo-mock-talent", slug: "giovane-regista-precedente", title: "Quando il giovane regista cambia la partita", summary: "Preview editoriale che collega un protagonista U21 mock a un profilo narrativo della Story Library.", type: "talent_echo", status: "approved", visibility: "public_preview", trigger: MOCK_HISTORICAL_ECHO_TRIGGERS[1], score: talentScore,
    explanation: "Ruolo e impatto sulla gara creano un'affinità narrativa; non costituiscono una comparazione di valore o una valutazione di scouting.", comparisonPoints: [{ id: "role", label: "Ruolo narrativo", modernValue: "Giovane decisivo", historicalValue: "Profilo talento", similarity: "partial" }],
    relatedStory: { storyId: "story-mock-talent", slug: "il-regista-tra-le-linee", title: "Il regista tra le linee", category: "talent_story", summary: "Anteprima mock di un profilo talento costruito con note originali." }, relatedMatches: [{ id: "mock-riviera-porto", label: "Riviera–Porto mock", scoreline: "2–1", dateLabel: "22 agosto 2026", isModern: true }], sources: [MOCK_HISTORICAL_ECHO_SOURCES[2]], editorialSuggestion: { headline: "Il precedente del giovane regista", angle: "Un profilo narrativo, non scouting certificato.", destinations: ["story_library", "substack"], status: "idea_only" }, internalWarnings: [], timeline: [], reviewedByHuman: true, autoPublished: false, createdAt: "2026-08-22T21:00:00.000Z", updatedAt: "2026-08-24T09:00:00.000Z",
  },
  {
    id: "echo-candidate-late", slug: "rimonta-da-valutare", title: "Una rimonta da confrontare", summary: "Candidato generato da un segnale moderno mock.", type: "comeback_echo", status: "candidate", visibility: "private_admin", trigger: { ...MOCK_HISTORICAL_ECHO_TRIGGERS[0], id: "trigger-late", type: "late_goal", label: "Gol decisivo oltre il 90°", strength: "medium" }, score: mediumScore, explanation: "La dinamica temporale suggerisce un possibile confronto, ma manca un precedente verificato specifico.", comparisonPoints: [], relatedStory: { storyId: "story-mock-4-4", slug: "il-4-4-che-si-ripete", title: "Il 4–4 che si ripete", category: "legendary_match", summary: "Storia mock." }, relatedMatches: [], sources: [MOCK_HISTORICAL_ECHO_SOURCES[0]], editorialSuggestion: { headline: "Il gol tardi che riapre la memoria", angle: "Verificare un precedente coerente.", destinations: ["future_article"], status: "idea_only" }, internalWarnings: ["Score sotto soglia editoriale.", "Precedente specifico assente."], timeline: [], reviewedByHuman: false, autoPublished: false, createdAt: "2026-08-23T21:00:00.000Z", updatedAt: "2026-08-23T21:00:00.000Z",
  },
  {
    id: "echo-pending-italy", slug: "connessione-italia-da-verificare", title: "Una connessione italiana da verificare", summary: "Ipotesi editoriale basata su una menzione ancora non confermata.", type: "italian_connection_echo", status: "pending_review", visibility: "private_admin", trigger: MOCK_HISTORICAL_ECHO_TRIGGERS[2], score: mediumScore, explanation: "La menzione è insufficiente senza una relazione storica documentata.", comparisonPoints: [], relatedStory: { storyId: "story-mock-4-4", slug: "il-4-4-che-si-ripete", title: "Il 4–4 che si ripete", category: "legendary_match", summary: "Storia mock usata soltanto per test." }, relatedMatches: [], sources: [MOCK_HISTORICAL_ECHO_SOURCES[3]], editorialSuggestion: { headline: "Il filo con l'Italia", angle: "Cercare fonti prima di sviluppare il contenuto.", destinations: ["future_article", "substack"], status: "idea_only" }, internalWarnings: ["Fonte non verificata.", "Collegamento narrativo debole."], timeline: [], reviewedByHuman: false, autoPublished: false, createdAt: "2026-08-23T08:00:00.000Z", updatedAt: "2026-08-24T08:00:00.000Z",
  },
  {
    id: "echo-rejected-tactical", slug: "somiglianza-tattica-rifiutata", title: "Somiglianza tattica rifiutata", summary: "Test di falso positivo bloccato.", type: "tactical_echo", status: "rejected", visibility: "private_admin", trigger: MOCK_HISTORICAL_ECHO_TRIGGERS[3], score: lowScore, explanation: "Una parola chiave condivisa non dimostra una continuità tattica.", comparisonPoints: [], relatedStory: { storyId: "story-mock-4-4", slug: "il-4-4-che-si-ripete", title: "Il 4–4 che si ripete", category: "legendary_match", summary: "Storia mock." }, relatedMatches: [], sources: [], editorialSuggestion: { headline: "Nessun contenuto", angle: "Candidato rifiutato.", destinations: [], status: "idea_only" }, internalWarnings: ["Score basso.", "Falso positivo probabile."], timeline: [], reviewedByHuman: true, autoPublished: false, createdAt: "2026-08-24T08:00:00.000Z", updatedAt: "2026-08-24T08:30:00.000Z",
  },
];
