import { collectWeeklyDigestSignals } from "./weeklyDigestCollector";
import { formatWeeklyDigest } from "./weeklyDigestFormatter";
import { mapWeeklySignalToCandidate } from "./weeklyDigestMappers";
import { assertWeeklyDigestExternalCallsDisabled } from "./weeklyDigestRules";
import type { WeeklyDigest, WeeklyDigestItem, WeeklyDigestRunMode, WeeklyDigestRunResult, WeeklyDigestSection, WeeklyDigestSectionType, WeeklyDigestSignal } from "./weeklyDigestTypes";

const priorityWeight = { urgent: 4, high: 3, medium: 2, low: 1 } as const;
const itemFrom = (signal: WeeklyDigestSignal, factLabel: WeeklyDigestItem["factLabel"] = "signal"): WeeklyDigestItem => ({ id: `weekly-item-${signal.id}`, title: signal.title, summary: signal.summary, sourceIds: [...signal.sourceIds], signalId: signal.id, factLabel, officialUrl: null });
const placeholder = (id: string, title: string, summary: string): WeeklyDigestItem => ({ id, title, summary, sourceIds: [], signalId: null, factLabel: "to_verify", officialUrl: null });
const fill = (signals: readonly WeeklyDigestSignal[], count: number, prefix: string): WeeklyDigestItem[] => [...signals.slice(0, count).map((signal) => itemFrom(signal)), ...Array.from({ length: Math.max(0, count - signals.length) }, (_, index) => placeholder(`${prefix}-${index}`, `${prefix} ${signals.length + index + 1}`, "Non disponibile senza una fonte verificata."))];
const section = (type: WeeklyDigestSectionType, title: string, description: string, items: WeeklyDigestItem[], visibility: WeeklyDigestSection["visibility"]): WeeklyDigestSection => ({ id: `weekly-section-${type}`, type, title, description, items, visibility, requiresHumanReview: true });

function buildSections(signals: readonly WeeklyDigestSignal[]): WeeklyDigestSection[] { const stories = signals.filter((signal) => signal.type === "official_news" || signal.type === "article_seed" || signal.type === "historical_echo"); const talents = signals.filter((signal) => signal.type === "young_player" || signal.type === "talent_signal" || signal.type === "stats_spike"); const videos = signals.filter((signal) => signal.type === "video_watch" && signal.verifiedSources && !signal.warningCodes.includes("copyright_uncertain")); const crazy = signals.filter((signal) => signal.crazyMatch); const echoes = signals.filter((signal) => signal.type === "historical_echo"); const minor = signals.filter((signal) => signal.type === "minor_league_signal" || signal.type === "apify_weekly_signal"); const italy = signals.filter((signal) => signal.italianConnection || signal.type === "italian_connection" || signal.type === "ex_serie_a"); const stats = signals.filter((signal) => signal.type === "stats_spike"); const article = signals.filter((signal) => signal.type === "article_seed"); const substack = signals.filter((signal) => signal.type === "newsletter_seed"); const reels = signals.filter((signal) => signal.type === "reel_seed"); const creators = signals.filter((signal) => signal.type === "creator_pack_seed"); return [
  section("weekly_opening", "Apertura settimana", "Introduzione editoriale", [placeholder("weekly-opening", "La settimana in una domanda", "Apertura originale da approvare, senza promesse di dati live.")], "free_candidate"),
  section("top_stories", "3 storie", "Selezione narrativa", fill(stories, 3, "Storia"), "free_candidate"),
  section("top_talents", "3 talenti", "Segnali prudenti, non scouting certificato", fill(talents, 3, "Talento"), "free_candidate"),
  section("video_watchlist", "3 link/video ufficiali", "Solo URL ufficiali verificati", fill(videos, 3, "Link ufficiale"), "free_candidate"),
  section("crazy_matches", "Partita pazza", "Match trigger da revisionare", crazy.slice(0, 1).map((signal) => itemFrom(signal)), "free_candidate"),
  section("historical_echoes", "Historical Echo", "Confronto prudente", echoes.slice(0, 2).map((signal) => itemFrom(signal, "editorial_opinion")), "free_candidate"),
  section("minor_league_report", "Campionati minori", "Solo snapshot Apify weekly mock/salvati", minor.map((signal) => itemFrom(signal, "to_verify")), "paid_candidate"),
  section("italy_connections", "Collegamenti italiani", "Italia Radar da verificare", italy.map((signal) => itemFrom(signal, "hypothesis")), "paid_candidate"),
  section("stats_signals", "Segnali statistici", "FULL_OFFICIAL mock", stats.map((signal) => itemFrom(signal)), "paid_candidate"),
  section("article_candidates", "Possibili articoli", "Semi editoriali", article.slice(0, 4).map((signal) => itemFrom(signal)), "internal"),
  section("substack_candidates", "Possibili contenuti Substack", "Free/paid da decidere", substack.slice(0, 4).map((signal) => itemFrom(signal)), "internal"),
  section("reel_candidates", "Possibili Reel", "Script testuali, nessun video", reels.slice(0, 4).map((signal) => itemFrom(signal)), "internal"),
  section("creator_pack", "Creator Pack", "Idee private", creators.slice(0, 3).map((signal) => itemFrom(signal)), "internal"),
  section("review_checklist", "Checklist review", "Controlli obbligatori", ["Fonti e seconde fonti", "Nomi, date e punteggi", "Rumor e rettifiche", "Diritti video/immagini", "Link ufficiali", "Separazione free/paid/internal", "CTA e destinazioni"].map((title, index) => placeholder(`weekly-check-${index}`, title, "Controllo umano pending.")), "internal"),
]; }

export function runWeeklyDigest(input: { digestId: string; weekStart: string; weekEnd: string; title?: string; mode?: WeeklyDigestRunMode; signalLimit?: number }): WeeklyDigestRunResult { const collected = collectWeeklyDigestSignals(); const signals = collected.signals.slice(0, input.signalLimit ?? collected.signals.length); const candidates = signals.map((signal) => mapWeeklySignalToCandidate(signal, collected.sources)).sort((a, b) => priorityWeight[b.priority] - priorityWeight[a.priority] || b.score.value - a.score.value || a.id.localeCompare(b.id)); const base = { id: input.digestId, weekStart: input.weekStart, weekEnd: input.weekEnd, title: input.title ?? `Weekly Digest ${input.weekStart} / ${input.weekEnd}`, status: signals.length ? "generated" as const : "draft" as const, visibility: "private_admin" as const, sections: buildSections(signals), signals, sources: collected.sources.filter((source) => signals.some((signal) => signal.sourceIds.includes(source.id)) || source.type === "daily_radar"), candidates, reviewStatus: candidates.some((candidate) => candidate.reviewStatus === "blocked") ? "needs_sources" as const : "not_reviewed" as const, autoPublish: false as const, autoSend: false as const, autoProduce: false as const, createdAt: `${input.weekEnd}T18:00:00.000Z`, updatedAt: `${input.weekEnd}T18:00:00.000Z` }; const digest: WeeklyDigest = { ...base, exportPreview: formatWeeklyDigest(base) }; return { mode: input.mode ?? "mock", digest, success: signals.length > 0, warnings: [...collected.warnings, assertWeeklyDigestExternalCallsDisabled().reason], providerCalls: 0, apifyCalls: 0, externalAiCalls: 0, substackApiCalls: 0, emailsSent: 0, videosProduced: 0, networkCalls: 0, filesWritten: 0, databaseWrites: 0, published: false, userSearchQuotaConsumed: 0, schedulerCreated: false }; }
