import { COMPETITIONS } from "@/config/competitions";
import { PROVIDERS } from "@/config/providers";
import type { AdminApiUsage, AdminBudgetUsage, AdminCompetition, AdminContentQueueItem, AdminImportLog, AdminOverview, AdminProvider, AdminUser } from "./adminTypes";

export const MOCK_ADMIN_COMPETITIONS: AdminCompetition[] = COMPETITIONS.map((item) => ({ id: item.id, name: item.name, trackingLevel: item.tracking_level, provider: item.primary_provider, publicStats: item.public_stats_enabled, apifyPriority: item.apify_priority, status: "mock", note: item.tracking_level === "full_official" ? "Provider stabile futuro; fallback mock." : "Import esterno non operativo." }));
export const MOCK_ADMIN_PROVIDERS: AdminProvider[] = PROVIDERS.map((item) => ({ id: item.id, name: item.name, type: item.type, status: item.id === "mock_provider" ? "mock" : item.active ? "active" : "inactive", priority: item.priority, monthlyBudgetEur: item.monthly_budget_eur, note: item.notes, realCalls: 0, tokenExposed: false }));
export const MOCK_APIFY_USAGE: AdminBudgetUsage = { label: "Apify / SofaScore", currentEur: 0, warningEur: 24, hardStopEur: 30, maximumEur: 30, remainingEur: 30, p1Planned: 15, p2Planned: 14, realRuns: 0, status: "dry_run", warnings: ["Costi mock: nessuna run reale contabilizzata.", "Termini, licenze e actor devono essere approvati."] };
export const MOCK_API_USAGE: AdminApiUsage = { provider: "Stable provider da scegliere", dailyBudget: null, monthlyBudget: null, realRequests: 0, mockLogEntries: 4, status: "not_connected", note: "Budget e credenziali non configurati; nessun token viene letto o mostrato." };
export const MOCK_IMPORTS: AdminImportLog[] = [
  { id: "import-competitions", label: "Competizioni e squadre", scope: "43 competizioni / 86 squadre mock", mode: "dry_run", status: "dry_run", recordsPrepared: 129, realCalls: 0, writes: 0, previousDataPreserved: true, note: "Payload preparati, nessun upsert." },
  { id: "import-matches", label: "Partite e risultati", scope: "Fixtures, risultati, eventi", mode: "dry_run", status: "dry_run", recordsPrepared: 172, realCalls: 0, writes: 0, previousDataPreserved: true, note: "Snapshot precedente preservato." },
  { id: "import-full-stats", label: "Statistiche FULL", scope: "Solo 14 FULL_OFFICIAL", mode: "mock", status: "mock", recordsPrepared: 168, realCalls: 0, writes: 0, previousDataPreserved: true, note: "Metriche mock, Apify escluso." },
  { id: "import-apify", label: "Apify weekly", scope: "15 P1 + 14 P2", mode: "dry_run", status: "dry_run", recordsPrepared: 0, realCalls: 0, writes: 0, previousDataPreserved: true, note: "Piano soltanto; run reali 0." },
];
export const MOCK_CONTENT_QUEUE: AdminContentQueueItem[] = [
  { id: "content-1", area: "content_radar", title: "Partita 4–4 da valutare", status: "pending_review", visibility: "private_admin", note: "Trigger mock; nessuna pubblicazione automatica." },
  { id: "news-1", area: "news_radar", title: "News Radar non collegato", status: "draft", visibility: "private_admin", note: "Nessuna fonte o rumor acquisito." },
  { id: "video-1", area: "video_radar", title: "Talento della settimana", status: "approved", visibility: "private_admin", note: "Script originale mock; nessuna clip." },
  { id: "highlight-1", area: "highlight_links", title: "Link ufficiale da configurare", status: "pending_review", visibility: "private_admin", note: "URL assente; download vietato." },
  { id: "story-1", area: "story_library", title: "Archivio storico placeholder", status: "draft", visibility: "private_admin", note: "Nessun PDF/Markdown importato." },
  { id: "echo-1", area: "historical_echo", title: "Historical Echo 4–4", status: "pending_review", visibility: "private_admin", note: "Collegamento narrativo mock." },
  { id: "substack-1", area: "substack", title: "Digest settimanale free", status: "draft", visibility: "private_admin", note: "Nessuna API o pubblicazione automatica." },
  { id: "generated-1", area: "generated_content", title: "Bozza generata placeholder", status: "pending_review", visibility: "private_admin", note: "Revisione umana obbligatoria." },
];
export const MOCK_ADMIN_USERS: AdminUser[] = [{ id: "mock-admin", displayName: "Amministratore mock", role: "admin_mock", advancedSearchesUsed: 0, searchLimit: 3, paymentStatus: "not_applicable", status: "mock" }, { id: "mock-free", displayName: "Utente free mock", role: "free_user", advancedSearchesUsed: 2, searchLimit: 3, paymentStatus: "not_applicable", status: "mock" }];
export const MOCK_ADMIN_OVERVIEW: AdminOverview = { projectStatus: "mock_safe", completedSteps: 18, connectedToSupabase: false, realActionsEnabled: false, stats: [{ id: "competitions", label: "Competizioni", value: 43, status: "mock", note: "14 FULL, 15 P1, 14 P2" }, { id: "providers", label: "Provider operativi", value: "1 mock", status: "mock", note: "Provider reali disattivi" }, { id: "pending", label: "Pending review", value: MOCK_CONTENT_QUEUE.filter((item) => item.status === "pending_review").length, status: "pending_review", note: "Nessuna pubblicazione automatica" }, { id: "users", label: "Utenti", value: MOCK_ADMIN_USERS.length, status: "mock", note: "Record dimostrativi" }], warnings: [{ id: "access", level: "critical", title: "Protezione admin mock", message: "Non distribuire in produzione prima di Auth/RBAC/RLS." }, { id: "database", level: "warning", title: "Supabase non collegato", message: "Tutti i dati e i log sono in memoria." }, { id: "actions", level: "info", title: "Azioni reali disabilitate", message: "Nessun bottone di scrittura o operazione distruttiva." }] };
