import { generateNewsletterDraft } from "./newsletterDraftGenerator";

export const MOCK_NEWSLETTER_DRAFTS = [
  generateNewsletterDraft({ draftId: "newsletter-weekly-free", workingTitle: "Il radar della settimana — edizione mock", format: "weekly_digest", plan: "free", tone: "clear_editorial", destination: "substack_free", sourceRefs: [{ type: "story_library", id: "story-mock-4-4" }, { type: "story_library", id: "story-mock-talent" }, { type: "news_radar", id: "news-official-injury" }, { type: "news_radar", id: "news-talent" }, { type: "historical_echo", id: "echo-mock-4-4" }, { type: "video_radar", id: "vr-talent-week" }, { type: "video_radar", id: "vr-crazy-match" }, { type: "video_radar", id: "vr-tactical" }, { type: "match_trigger", id: "mock-aurora-borgo" }] }),
  generateNewsletterDraft({ draftId: "newsletter-talent-paid", workingTitle: "Talent Radar — segnali da seguire", format: "talent_radar", plan: "paid", tone: "cautious", destination: "substack_paid", sourceRefs: [{ type: "news_radar", id: "news-talent" }, { type: "story_library", id: "story-mock-talent" }, { type: "article_draft", id: "draft-talent-video" }, { type: "video_radar", id: "vr-talent-week" }] }),
  generateNewsletterDraft({ draftId: "newsletter-minor-paid", workingTitle: "Campionati minori — report mock", format: "minor_league_report", plan: "paid", tone: "analytical", destination: "substack_paid", sourceRefs: [{ type: "news_radar", id: "news-data-candidate" }, { type: "news_radar", id: "news-talent" }, { type: "match_trigger", id: "mock-aurora-borgo" }] }),
  generateNewsletterDraft({ draftId: "newsletter-echo-mixed", workingTitle: "Historical Echo — otto gol, due epoche", format: "historical_echo_digest", plan: "mixed", tone: "narrative", destination: "weekly_digest", sourceRefs: [{ type: "historical_echo", id: "echo-mock-4-4" }, { type: "story_library", id: "story-mock-4-4" }, { type: "article_draft", id: "draft-echo-4-4" }, { type: "match_trigger", id: "mock-aurora-borgo" }] }),
  generateNewsletterDraft({ draftId: "newsletter-video-paid", workingTitle: "Video Watchlist — cosa osservare", format: "video_watchlist", plan: "paid", tone: "concise", destination: "substack_paid", sourceRefs: [{ type: "video_radar", id: "vr-talent-week" }, { type: "video_radar", id: "vr-crazy-match" }, { type: "video_radar", id: "vr-tactical" }] }),
  generateNewsletterDraft({ draftId: "newsletter-creator-internal", workingTitle: "Creator Pack — idee private", format: "creator_pack", plan: "internal_only", tone: "creator_friendly", destination: "private_note", sourceRefs: [{ type: "article_draft", id: "draft-talent-video" }, { type: "historical_echo", id: "echo-mock-4-4" }, { type: "video_radar", id: "vr-history" }] }),
  generateNewsletterDraft({ draftId: "newsletter-blocked-empty", workingTitle: "Bozza senza fonti", format: "article_roundup", plan: "internal_only", tone: "clear_editorial", destination: "private_note", sourceRefs: [] }),
].map((result) => result.draft);
