import { MOCK_ARTICLE_DRAFTS } from "../articleGenerator/mockArticleDrafts";
import { MOCK_HISTORICAL_ECHO_DATA } from "../historicalEcho/mockHistoricalEchoData";
import { MOCK_NEWS_RADAR_DATA } from "../newsRadar/mockNewsRadarData";
import { checkNewsRadarRules } from "../newsRadar/newsRadarRules";
import { MOCK_STORY_LIBRARY } from "../storyLibrary/mockStoryLibrary";
import { MOCK_VIDEO_RADAR_ITEMS } from "../videoRadar/mockVideoRadarData";
import type { NewsletterDraftGenerationInput, NewsletterDraftSource, NewsletterRiskFlag, NewsletterSourceCollectionResult } from "./newsletterGeneratorTypes";

function storySource(id: string): NewsletterDraftSource | null { const item = MOCK_STORY_LIBRARY.find((story) => story.id === id || story.slug === id); if (!item) return null; const ready = item.status === "approved" || item.status === "published"; return { id: `newsletter-story-${item.id}`, type: "story_library", referenceId: item.id, label: item.title, shortSummary: item.summary, referenceUrl: null, factConfidence: ready ? "likely" : "unknown", riskFlags: ready ? ["copyright"] : ["copyright", "unverified_data"], verifiedForDraft: ready, officialLinkVerified: false, copiedLongText: false, downloadedVideo: false }; }

function newsSource(id: string): NewsletterDraftSource | null { const item = MOCK_NEWS_RADAR_DATA.find((news) => news.id === id || news.slug === id); if (!item) return null; const check = checkNewsRadarRules(item); const flags: NewsletterRiskFlag[] = []; if (item.signals.some((signal) => signal.type === "rumor_da_verificare")) flags.push("rumor", "unverified_data"); if (item.category === "injury_update") flags.push("injury"); if (item.category === "controversy") flags.push("controversy"); if (item.category === "talent_signal") flags.push("scouting_claim"); if (!check.publicEligible) flags.push("unverified_data"); const official = item.sources.some((source) => source.reliability === "official"); return { id: `newsletter-news-${item.id}`, type: "news_radar", referenceId: item.id, label: item.title, shortSummary: item.summary, referenceUrl: null, factConfidence: official && check.publicEligible ? "verified" : check.publicEligible ? "likely" : "uncertain", riskFlags: [...new Set(flags)], verifiedForDraft: check.publicEligible, officialLinkVerified: false, copiedLongText: false, downloadedVideo: false }; }

function echoSource(id: string): NewsletterDraftSource | null { const item = MOCK_HISTORICAL_ECHO_DATA.find((echo) => echo.id === id || echo.slug === id); if (!item) return null; const ready = item.reviewedByHuman && (item.status === "approved" || item.status === "published"); return { id: `newsletter-echo-${item.id}`, type: "historical_echo", referenceId: item.id, label: item.title, shortSummary: item.summary, referenceUrl: null, factConfidence: ready ? "likely" : "uncertain", riskFlags: ready ? [] : ["unverified_data"], verifiedForDraft: ready, officialLinkVerified: false, copiedLongText: false, downloadedVideo: false }; }

function videoSource(id: string): NewsletterDraftSource | null { const item = MOCK_VIDEO_RADAR_ITEMS.find((video) => video.id === id || video.slug === id); if (!item) return null; const ready = item.status === "approved"; const official = ready && Boolean(item.officialVideoUrl); return { id: `newsletter-video-${item.id}`, type: "video_radar", referenceId: item.id, label: item.title, shortSummary: item.summary, referenceUrl: official ? item.officialVideoUrl : null, factConfidence: "opinion", riskFlags: ["video_rights", ...(official ? [] : ["unofficial_highlight" as const]), ...(ready ? [] : ["unverified_data" as const])], verifiedForDraft: ready, officialLinkVerified: official, copiedLongText: false, downloadedVideo: false }; }

function articleSource(id: string): NewsletterDraftSource | null { const item = MOCK_ARTICLE_DRAFTS.find((draft) => draft.id === id || draft.slug === id); if (!item) return null; const flags: NewsletterRiskFlag[] = item.risks.flatMap((risk) => risk.code === "missing_source" ? ["unverified_data" as const] : risk.code === "video_rights" ? ["video_rights" as const] : risk.code === "copyright" ? ["copyright" as const] : risk.code === "rumor" ? ["rumor" as const] : risk.code === "injury" ? ["injury" as const] : risk.code === "controversy" ? ["controversy" as const] : risk.code === "assertive_claim" ? ["assertive_claim" as const] : risk.code === "unverified_data" ? ["unverified_data" as const] : []); return { id: `newsletter-article-${item.id}`, type: "article_draft", referenceId: item.id, label: item.title, shortSummary: item.subtitle, referenceUrl: null, factConfidence: item.riskLevel === "low" || item.riskLevel === "medium" ? "likely" : "uncertain", riskFlags: [...new Set(flags)], verifiedForDraft: item.riskLevel !== "blocked", officialLinkVerified: false, copiedLongText: false, downloadedVideo: false }; }

function matchSource(id: string): NewsletterDraftSource | null { const owner = MOCK_HISTORICAL_ECHO_DATA.find((echo) => echo.relatedMatches.some((match) => match.id === id)); const item = owner?.relatedMatches.find((match) => match.id === id); if (!owner || !item) return null; const ready = owner.reviewedByHuman && (owner.status === "approved" || owner.status === "published"); return { id: `newsletter-match-${item.id}`, type: "match_trigger", referenceId: item.id, label: `${item.label} ${item.scoreline}`, shortSummary: `Trigger partita mock collegato a ${owner.title}; data indicata: ${item.dateLabel}.`, referenceUrl: null, factConfidence: ready ? "likely" : "uncertain", riskFlags: ready ? [] : ["unverified_data"], verifiedForDraft: ready, officialLinkVerified: false, copiedLongText: false, downloadedVideo: false }; }

export function collectNewsletterSources(input: Pick<NewsletterDraftGenerationInput, "sourceRefs">): NewsletterSourceCollectionResult { const sources: NewsletterDraftSource[] = []; const missingRefs: NewsletterDraftGenerationInput["sourceRefs"] = []; for (const ref of input.sourceRefs) { const source = ref.type === "story_library" ? storySource(ref.id) : ref.type === "news_radar" ? newsSource(ref.id) : ref.type === "historical_echo" ? echoSource(ref.id) : ref.type === "video_radar" ? videoSource(ref.id) : ref.type === "article_draft" ? articleSource(ref.id) : matchSource(ref.id); if (source) sources.push(source); else missingRefs.push(ref); } const unique = sources.filter((source, index) => sources.findIndex((candidate) => candidate.id === source.id) === index); return { sources: unique, missingRefs, warnings: [...(missingRefs.length ? [`${missingRefs.length} riferimenti mock non risolti.`] : []), ...(unique.length === 0 ? ["Nessuna fonte raccolta: bozza newsletter bloccata."] : [])] }; }
