import { formatNewsletterAsMarkdown } from "./newsletterMarkdownFormatter";
import { buildNewsletterPrompt } from "./newsletterPromptBuilder";
import { buildNewsletterReviewChecklist } from "./newsletterReviewRules";
import { evaluateNewsletterRisks } from "./newsletterRiskRules";
import { collectNewsletterSources } from "./newsletterSourceCollector";
import type { NewsletterDraft, NewsletterDraftGenerationInput, NewsletterDraftGenerationResult, NewsletterDraftSection, NewsletterDraftSource, NewsletterFactConfidence } from "./newsletterGeneratorTypes";

const FIXED_TIME = "2026-08-25T14:00:00.000Z";
const slugify = (value: string) => value.toLocaleLowerCase("it-IT").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 80) || "newsletter-draft";
const ids = (sources: readonly NewsletterDraftSource[]) => sources.map((source) => source.id);
const summary = (source: NewsletterDraftSource) => `${source.label}: ${source.shortSummary}`;
const section = (id: string, title: string, purpose: string, sources: readonly NewsletterDraftSource[], fallback: string[], confidence: NewsletterFactConfidence = "opinion", paidOnly = false): NewsletterDraftSection => ({ id, title, purpose, items: sources.length ? sources.map(summary) : fallback, factConfidence: sources.length ? confidence : "unknown", sourceIds: ids(sources), paidOnly });
const fillSlots = (sources: readonly NewsletterDraftSource[], count: number, emptyLabel: string) => [...sources.slice(0, count).map(summary), ...Array.from({ length: Math.max(0, count - sources.length) }, (_, index) => `${emptyLabel} ${sources.length + index + 1}: non disponibile senza fonte verificata.`)];

function buildSections(input: NewsletterDraftGenerationInput, sources: readonly NewsletterDraftSource[]): NewsletterDraftSection[] {
  const stories = sources.filter((source) => source.type === "story_library" || source.type === "article_draft" || source.type === "news_radar");
  const talents = sources.filter((source) => /talent|giovane|regista|u21/i.test(`${source.label} ${source.shortSummary}`));
  const videos = sources.filter((source) => source.type === "video_radar");
  const officialVideos = videos.filter((source) => source.officialLinkVerified && source.referenceUrl);
  const matches = sources.filter((source) => source.type === "match_trigger");
  const echoes = sources.filter((source) => source.type === "historical_echo" || source.type === "story_library");
  const uncertain = sources.filter((source) => !source.verifiedForDraft || source.riskFlags.length > 0);
  const cta = section("cta", "CTA Substack/sito", "Proposta da approvare", [], ["CTA proposta: invita a leggere sul sito o sul canale Substack appropriato, senza promesse eccessive."], "opinion", input.plan === "paid");

  if (input.format === "weekly_digest") return [
    section("opening", "Apertura", "Introduzione editoriale", [], ["Apertura mock: presenta la settimana con tono chiaro e senza promesse di dati live."], "opinion"),
    { ...section("stories", "3 storie", "Selezione narrativa", stories, [], "likely"), items: fillSlots(stories, 3, "Storia") },
    { ...section("talents", "3 talenti da seguire", "Profili prudenti", talents, [], "likely"), items: fillSlots(talents, 3, "Talento") },
    { ...section("videos", "3 video/link highlights ufficiali", "Solo link verificati", officialVideos, [], "verified"), items: fillSlots(officialVideos, 3, "Link ufficiale") },
    section("crazy", "Partita pazza", "Trigger revisionato", matches, ["Nessuna partita pazza selezionata con fonte sufficiente."], "likely"),
    section("echo", "Historical Echo", "Collegamento prudente", echoes, ["Nessun collegamento storico approvato selezionato."], "likely"),
    cta,
  ];
  if (input.format === "talent_radar") return [section("talents", "Talenti da seguire", "Profili", talents, ["Nessun talento verificato selezionato."], "likely", input.plan === "paid"), section("why", "Perché sono interessanti", "Angolo editoriale", talents, ["Motivazioni da costruire senza scouting certificato."], "opinion", input.plan === "paid"), section("data", "Dati e segnali disponibili", "Evidenze", sources, ["Nessun dato disponibile."], "likely", input.plan === "paid"), section("verify", "Cosa verificare", "Fact-check", uncertain, ["Controllare comunque fonti, nomi, età, ruolo e campione osservato."], "unknown", input.plan === "paid"), cta];
  if (input.format === "minor_league_report") return [section("leagues", "Campionati minori", "Panoramica", sources, ["Nessun campionato minore selezionato."], "likely", true), section("p1p2", "Segnali P1/P2", "Copertura disponibile", sources.filter((source) => source.type === "minor_league_signal" || source.type === "news_radar"), ["Nessun segnale P1/P2 strutturato selezionato."], "uncertain", true), section("crazy", "Partite pazze", "Match revisionati", matches, ["Nessuna partita disponibile."], "likely", true), section("talents", "Talenti", "Profili da seguire", talents, ["Nessun talento verificato."], "likely", true), section("italy", "Collegamenti italiani", "Italia Radar", sources.filter((source) => /italia|serie a/i.test(`${source.label} ${source.shortSummary}`)), ["Nessun collegamento italiano verificato."], "uncertain", true), cta];
  if (input.format === "historical_echo_digest") return [section("modern", "Evento moderno", "Punto di partenza", matches.length ? matches : sources.filter((source) => source.type === "news_radar"), ["Evento moderno non disponibile."], "likely"), section("story", "Storia collegata", "Story Library", echoes, ["Storia collegata non disponibile."], "likely"), section("comparison", "Confronto prudente", "Somiglianze e differenze", echoes, ["Confronto da verificare."], "opinion"), section("angle", "Spunto editoriale", "Idea, non fatto", sources, ["Nessuno spunto disponibile."], "opinion"), cta];
  if (input.format === "video_watchlist") return [section("links", "Link ufficiali/verificati", "Soltanto fonti autorizzate", officialVideos, ["Nessun link ufficiale verificato: non inserire URL o video."], "verified", input.plan === "paid"), section("watch", "Cosa guardare", "Watchlist", videos, ["Nessun elemento Video Radar selezionato."], "opinion", input.plan === "paid"), section("why", "Perché è interessante", "Angolo originale", videos, ["Motivazione da sviluppare."], "opinion", input.plan === "paid"), section("rights", "Diritti e limiti", "Nessun download", [], ["Non scaricare, ritagliare o ricaricare clip; usare soltanto link ufficiali verificati."], "verified", input.plan === "paid"), cta];
  if (input.format === "creator_pack") return [section("reels", "Idee Reel", "Concept originali", sources, ["Nessuna idea selezionata."], "opinion", true), section("hooks", "Hook", "Aperture non clickbait", sources, ["Hook da sviluppare con tono prudente."], "opinion", true), section("seeds", "Script seed", "Outline, non script finale", sources, ["Nessun seed disponibile."], "opinion", true), section("angles", "Angoli editoriali", "Prospettive", sources, ["Nessun angolo disponibile."], "opinion", true), cta];
  return [section("opening", "Apertura", "Introduzione", [], ["Apertura mock da revisionare."], "opinion"), section("roundup", "Contenuti selezionati", "Riepilogo", sources, ["Nessuna fonte disponibile."], "likely", input.plan === "paid"), section("verify", "Cosa verificare", "Fact-check", uncertain, ["Controllare tutte le fonti e i dati."], "unknown"), cta];
}

export function generateNewsletterDraft(input: NewsletterDraftGenerationInput): NewsletterDraftGenerationResult { const collection = collectNewsletterSources(input); const title = input.workingTitle?.trim() || `Bozza ${input.format.replace(/_/g, " ")}`; const subject = input.subject?.trim() || title; const preheader = `Bozza ${input.plan} costruita da ${collection.sources.length} fonti mock; review obbligatoria.`; const sections = buildSections(input, collection.sources); const risk = evaluateNewsletterRisks({ title, subject, sources: collection.sources, sections }); const id = input.draftId ?? `newsletter-${slugify(title)}-${input.format}`; const base: NewsletterDraft = { id, slug: slugify(title), title, subject, preheader, status: collection.sources.length ? "generated" : "draft", visibility: "private_admin", format: input.format, plan: input.plan, tone: input.tone, destination: input.destination, sections, sources: collection.sources, risks: risk.risks, riskLevel: risk.riskLevel, reviewChecklist: buildNewsletterReviewChecklist(risk.riskLevel), internalPrompt: buildNewsletterPrompt(input, collection.sources), markdownPreview: "", reviewedByHuman: false, generatedWithoutExternalAi: true, autoPublish: false, autoSend: false, createdAt: FIXED_TIME, updatedAt: FIXED_TIME }; const markdown = formatNewsletterAsMarkdown(base); const draft = { ...base, markdownPreview: markdown }; return { success: collection.sources.length > 0, draft, markdown, warnings: [...collection.warnings, ...risk.risks.map((item) => item.message)], externalAiCalls: 0, substackApiCalls: 0, emailsSent: 0, networkCalls: 0, filesWritten: 0, databaseWrites: 0, published: false, sent: false }; }
