import { checkStoryCopyright } from "./storyCopyrightRules";
import type { StoryCategory, StoryFormat, StoryImportPreview, StoryMarkdownFrontmatter, StorySourceType, StoryVisibility } from "./storyTypes";
const CATEGORIES = new Set<StoryCategory>(["legendary_match", "player_profile", "team_story", "tactical_story", "transfer_story", "underdog_story", "rivalry", "record", "comeback", "scandal_or_controversy", "cultural_story", "italian_connection", "historical_echo", "talent_story"]);
const FORMATS = new Set<StoryFormat>(["short_story", "longform_outline", "profile", "timeline", "historical_note", "video_script_seed"]);
const SOURCE_TYPES = new Set<StorySourceType>(["original_note", "markdown_file", "pdf_reference", "book_reference", "article_reference", "video_reference", "official_source", "database_trigger", "manual_research"]);
const VISIBILITIES = new Set<StoryVisibility>(["private_admin", "public_preview", "public_full", "substack_only", "paid_substack_candidate"]);

function parseScalar(value: string): string { return value.trim().replace(/^['"]|['"]$/g, ""); }
/** Parser string-only: non accede al filesystem e non pubblica. */
export function parseMarkdownStory(markdown: string): StoryImportPreview { const errors: string[] = []; const warnings: string[] = []; const parts = markdown.startsWith("---\n") ? markdown.split(/^---\s*$/m) : []; if (parts.length < 3) errors.push("Frontmatter delimitato da --- mancante."); const rawFrontmatter = parts[1] ?? ""; const body = (parts.slice(2).join("---").trim()); const values: Record<string, string> = {}; for (const line of rawFrontmatter.split("\n")) { const separator = line.indexOf(":"); if (separator > 0) values[line.slice(0, separator).trim()] = parseScalar(line.slice(separator + 1)); } const frontmatter: Partial<StoryMarkdownFrontmatter> = { title: values.title, summary: values.summary, source_reference: values.source_reference };
  if (values.category && CATEGORIES.has(values.category as StoryCategory)) frontmatter.category = values.category as StoryCategory; else errors.push("category mancante o non valida.");
  if (values.format && FORMATS.has(values.format as StoryFormat)) frontmatter.format = values.format as StoryFormat; else errors.push("format mancante o non valido.");
  if (values.source_type && SOURCE_TYPES.has(values.source_type as StorySourceType)) frontmatter.source_type = values.source_type as StorySourceType; else errors.push("source_type mancante o non valido.");
  if (values.visibility && VISIBILITIES.has(values.visibility as StoryVisibility)) frontmatter.visibility = values.visibility as StoryVisibility;
  if (values.tags) frontmatter.tags = values.tags.split(",").map((tag) => tag.trim()).filter(Boolean).slice(0, 12);
  if (!values.title?.trim()) errors.push("title obbligatorio."); if (!values.summary?.trim()) errors.push("summary obbligatorio."); if (!values.source_reference?.trim()) errors.push("source_reference obbligatorio."); if (!body) errors.push("Corpo Markdown vuoto.");
  const copyright = checkStoryCopyright({ sourceType: frontmatter.source_type, body, sourceReference: frontmatter.source_reference, claimsOriginal: frontmatter.source_type === "original_note" }); warnings.push(...copyright.warnings); const valid = errors.length === 0 && copyright.allowed; return { status: copyright.blocked ? "blocked_copyright" : valid ? (copyright.requiresHumanReview ? "needs_review" : "valid_preview") : "invalid", valid, frontmatter, bodyPreview: body.slice(0, 500), bodyCharacterCount: body.length, sourceDetected: Boolean(frontmatter.source_reference), errors, warnings, copyright, autoPublish: false, wroteFiles: false, wroteDatabase: false }; }
