import type { StoryItem, StorySource } from "./storyTypes";

export const MOCK_STORY_SOURCES: StorySource[] = [
  { id: "source-original-4-4", type: "original_note", title: "Appunti originali sul 4–4 mock", author: "Redazione Regista Avanzato", publisher: null, sourceUrl: null, publishedAt: null, referenceNote: "Nota originale costruita su dati dimostrativi, senza testo esterno copiato.", reliability: "high", humanReviewRequired: false, copyrightedFullTextStored: false },
  { id: "source-official-archive", type: "official_source", title: "Archivio ufficiale da verificare", author: null, publisher: "Titolare da configurare", sourceUrl: null, publishedAt: null, referenceNote: "Solo metadati mock; nessun documento o testo integrale archiviato.", reliability: "medium", humanReviewRequired: true, copyrightedFullTextStored: false },
  { id: "source-book-reference", type: "book_reference", title: "Riferimento bibliografico mock", author: "Autore da verificare", publisher: "Editore da verificare", sourceUrl: null, publishedAt: null, referenceNote: "Scheda bibliografica placeholder; nessun brano del libro conservato.", reliability: "unverified", humanReviewRequired: true, copyrightedFullTextStored: false },
  { id: "source-trigger", type: "database_trigger", title: "Trigger risultato 4–4", author: null, publisher: null, sourceUrl: null, publishedAt: "2026-08-18", referenceNote: "Segnale strutturato mock, non una fonte narrativa sufficiente.", reliability: "medium", humanReviewRequired: true, copyrightedFullTextStored: false },
];

export const MOCK_STORY_LIBRARY: StoryItem[] = [
  { id: "story-mock-4-4", slug: "il-4-4-che-si-ripete", title: "Il 4–4 che si ripete", category: "legendary_match", status: "published", visibility: "public_full", format: "short_story", summary: "Una storia originale mock su una partita ricca di gol e il suo possibile eco storico.", originalBody: "Otto gol, due squadre che non smettono di attaccare e una domanda narrativa: dove abbiamo già visto un copione simile? Questo testo è originale e dimostrativo; ogni riferimento storico dovrà essere verificato prima dell'uso editoriale.", keyFacts: ["Risultato mock 4–4", "Otto gol complessivi", "Collegamento storico ancora da verificare"], sourceIds: ["source-original-4-4", "source-trigger"], relatedEntities: [{ type: "match", id: "mock-aurora-borgo", label: "Aurora FC 4–4 Borgo United" }, { type: "historical_echo", id: "echo-mock-4-4", label: "Historical Echo 4–4" }], timeline: [{ id: "timeline-match", dateLabel: "18 agosto 2026", title: "La partita mock", description: "Il trigger registra un risultato finale di 4–4.", sourceIds: ["source-trigger"] }, { id: "timeline-review", dateLabel: "24 agosto 2026", title: "Revisione editoriale", description: "La redazione prepara una nota originale e separa fatti da suggestioni.", sourceIds: ["source-original-4-4"] }], tags: ["4-4", "partita memorabile", "historical echo"], reviewStatus: "approved", reviewWarnings: ["I precedenti storici reali devono ancora essere verificati."], createdAt: "2026-08-20T09:00:00.000Z", updatedAt: "2026-08-24T09:00:00.000Z", publishedAt: "2026-08-24T10:00:00.000Z", originalOrReworked: true, autoPublished: false },
  { id: "story-mock-talent", slug: "il-regista-tra-le-linee", title: "Il regista tra le linee", category: "talent_story", status: "approved", visibility: "public_preview", format: "profile", summary: "Anteprima mock di un profilo talento costruito con note originali.", originalBody: "Il profilo completo resta una bozza editoriale interna. La preview descrive soltanto il tema, senza attribuire fatti non verificati a persone reali.", keyFacts: ["Profilo completamente fittizio", "Nessun dato personale reale"], sourceIds: ["source-original-4-4"], relatedEntities: [{ type: "player", id: "mock-luca-ferri", label: "Luca Ferri — profilo mock" }], timeline: [], tags: ["talento", "regista", "U21"], reviewStatus: "approved", reviewWarnings: [], createdAt: "2026-08-21T09:00:00.000Z", updatedAt: "2026-08-23T09:00:00.000Z", publishedAt: null, originalOrReworked: true, autoPublished: false },
  { id: "story-mock-pending", slug: "archivio-da-verificare", title: "Una rivalità da verificare", category: "rivalry", status: "pending_review", visibility: "private_admin", format: "longform_outline", summary: "Outline privata basata su riferimenti ancora incompleti.", originalBody: "Solo note di lavoro originali. Nessun testo esterno importato.", keyFacts: [], sourceIds: ["source-book-reference"], relatedEntities: [], timeline: [], tags: ["rivalità"], reviewStatus: "needs_sources", reviewWarnings: ["Fonte bibliografica non verificata.", "Fact-check necessario."], createdAt: "2026-08-22T09:00:00.000Z", updatedAt: "2026-08-22T09:00:00.000Z", publishedAt: null, originalOrReworked: true, autoPublished: false },
  { id: "story-mock-draft", slug: "underdog-bozza", title: "Underdog — bozza", category: "underdog_story", status: "draft", visibility: "private_admin", format: "historical_note", summary: "Bozza interna priva di fonti sufficienti.", originalBody: "Idea originale ancora da sviluppare.", keyFacts: [], sourceIds: [], relatedEntities: [], timeline: [], tags: ["underdog"], reviewStatus: "needs_sources", reviewWarnings: ["Aggiungere almeno una fonte verificabile."], createdAt: "2026-08-23T09:00:00.000Z", updatedAt: "2026-08-23T09:00:00.000Z", publishedAt: null, originalOrReworked: true, autoPublished: false },
  { id: "story-mock-rejected", slug: "testo-esterno-rifiutato", title: "Import esterno rifiutato", category: "cultural_story", status: "rejected", visibility: "private_admin", format: "longform_outline", summary: "Record che documenta un import mock bloccato.", originalBody: "Il testo esterno non viene conservato; rimangono soltanto metadati e motivo del rifiuto.", keyFacts: [], sourceIds: ["source-book-reference"], relatedEntities: [], timeline: [], tags: ["copyright"], reviewStatus: "rejected", reviewWarnings: ["Contenuto derivato troppo lungo nel test di import."], createdAt: "2026-08-24T08:00:00.000Z", updatedAt: "2026-08-24T08:00:00.000Z", publishedAt: null, originalOrReworked: true, autoPublished: false },
];

export const MOCK_MARKDOWN_STORY = `---
title: La rimonta che cambia il ritmo
category: comeback
format: short_story
source_type: original_note
source_reference: Appunti originali redazione
summary: Anteprima mock di una storia di rimonta.
visibility: private_admin
tags: rimonta, partita memorabile
---
Una breve nota originale usata soltanto per provare il parser in memoria. Nessun file viene letto e nulla viene pubblicato.`;
